<?php

return [
    'crescimento_forte' => 15.0,
    'crescimento_moderado' => 5.0,
    'estabilidade' => 5.0,
    'retracao_leve' => 15.0,
    'renovacao_alta' => 60.0,
    'renovacao_baixa' => 40.0,
    'diversidade_alta' => 5,
    'diversidade_baixa' => 2,
    'concentracao_categoria' => 60.0,
    'percentil_acima' => 75.0,
    'percentil_abaixo' => 25.0,
    'qualidade_alta' => 85.0,
    'qualidade_media' => 60.0,
    'faixa_etaria_concentracao' => 40.0,
    'variacao_atividades' => 5.0,
    'anos_tendencia' => 3,
    'recuperacao_retracao' => 5.0,
    'recuperacao_alta' => 5.0,
    'anomalia_variacao' => 30.0,
    'anomalia_extrema' => 50.0,
    'pares_minimo' => 3,
    'qualidade' => [
        'completude' => 40,
        'consistencia' => 30,
        'historico' => 20,
        'anomalias' => 10,
    ],
    'portes' => [
        ['codigo' => '01', 'min' => 1, 'max' => 10],
        ['codigo' => '02', 'min' => 11, 'max' => 20],
        ['codigo' => '03', 'min' => 21, 'max' => 40],
        ['codigo' => '04', 'min' => 41, 'max' => 70],
        ['codigo' => '05', 'min' => 71, 'max' => 120],
        ['codigo' => '06', 'min' => 121, 'max' => null],
    ],
];
